### ISSUE TITLE
[feature]: Implement test, deserialize and simulate methods

### ISSUE THREAD

**Issue by slayerjain** [keploy/typescript-sdk#12]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

These are the remaining keploy core SDK methods to be implemented

### Why should this be worked on?

To make the TS SDK functional

**Comment by re-Tick** [comment]
Implemented the methods in keploy class. Merged the PR regarding the changes. Please review [this](https://github.com/keploy/typescript-sdk/blob/8f3a37a5fa14d2e703a012e4d56552b133529424/src/keploy.ts#L207)

**Comment by re-Tick** [comment]
Changes have been merged. Closing this issue
