### ISSUE TITLE
[feature]: Generic method to serialize and deserialize objects 

### ISSUE THREAD

**Issue by slayerjain** [keploy/typescript-sdk#13]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

This is required to save and mock objects such as database objects. 

### Why should this be worked on?

This is an important feature of keploy to record and mock depencies.

**Comment by re-Tick** [comment]
Ceated a generic function called ProcessDep for encoding and decoding [here](https://github.com/keploy/typescript-sdk/blob/8f3a37a5fa14d2e703a012e4d56552b133529424/src/util.ts#L27).
