### ISSUE TITLE
[feature]: create sample typescript nodejs app

### ISSUE THREAD

**Issue by slayerjain** [keploy/typescript-sdk#14]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

A sample app is required for testing the capabilities of the typescript sdk

### Why should this be worked on?

It'll help devs test the SDK and users with SDK usage

**Comment by re-Tick** [comment]
Added a sample in [keploy/samples-typescript](https://github.com/keploy/samples-typescript) repo. In this [PR](https://github.com/keploy/samples-typescript/pull/4). Closing this issue
