### ISSUE TITLE
[feature]: Create middleware for a router

### ISSUE THREAD

**Issue by slayerjain** [keploy/typescript-sdk#15]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We need to write middleware in typescript to intercept traffic and inject dependencies when required. 

### Why should this be worked on?

This is basic feature for keploy to record/replay traffic.

**Comment by re-Tick** [comment]
Refer to this #18 PR

**Comment by re-Tick** [comment]
Have merged a PR. Please close this issue.
