### ISSUE TITLE
[refactor]: use camelcase for request body object keys

### ISSUE THREAD

**Issue by rajatsharma** [keploy/typescript-sdk#6]
Currently types for request body has snake case keys, this is required because our backend needs snake case keys for request body, eg.

```ts
type TestCaseRequest = {
  captured: number;
  app_id: string;
  uri: string;
  http_req: object;
  http_res: object;
};
```

But it is not a good practice to use snake case in Typescript or Javascript. These keys should be in camel case.

Now there are few ways to fix this:

- Create a body transformer functions that converts all keys to camel case.
- We use [sindresorhus/got](https://github.com/sindresorhus/got) for handling Http requests, so we can figure out if there is another way provided by the library.

If you have any other ideas you can comment on this issue.

For more info feel free to message at our [slack channel](https://join.slack.com/t/keploy/shared_invite/zt-12rfbvc01-o54cOG0X1G6eVJTuI_orSA).

**Comment by petergeorgas** [comment]
I am interested in tackling this. I think transforming a camelCase object to snake_case via functions is the easiest way to accomplish this. Should be fairly straightforward. Let me know your thoughts. I'm not familiar with got at all so I'm not sure if there's a better way.

**Comment by petergeorgas** [comment]
Would something like this work?

```ts
type KeployTestCaseRequest = {
  captured: number;
  app_id: string;
  uri: string;
  http_req: object;
  http_res: object;
};

type TestCaseRequest = {
  captured: number;
  appId: string;
  uri: string;
  httpReq: object;
  httpRes: object;
};

const transformTestCaseRequest = (
  tcs: TestCaseRequest
): KeployTestCaseRequest => {
  return {
    captured: tcs.captured,
    app_id: tcs.appId,
    uri: tcs.uri,
    http_req: tcs.httpReq,
    http_res: tcs.httpRes,
  };
};
```

And then for something like the `put` method:
```ts
private async put(tcs: TestCaseRequest) {
    const transformed_obj = transformTestCaseRequest(tcs)
    if (
      this.appConfig.filter.urlRegex &&
      transformed_obj.uri.match(this.appConfig.filter.urlRegex)
    ) {
      return;
    }

    const request = new Request();
    this.setKey(request);
    request.setHttpHeader("Content-Type", "application/json");

    return this.client.makeHttpRequest(
      request.post("regression/testcase", JSON.stringify(transformed_obj))
    );
  }
 ```

**Comment by rajatsharma** [comment]
Hey @petergeorgas, thanks for commenting to the issue. 
So I am thinking if we can generalise this method so we can use it for any object, not just `TestCaseRequest`.

something like, `transformBody` which transforms any request body, not just `TestCaseRequest`

**Comment by nwf03** [comment]
Would something like this `const camelToSnakeCase = str => str.replace(/[A-Z]/g, letter => `_${letter.toLowerCase()}`);` work? I found it here [https://stackoverflow.com/questions/54246477/how-to-convert-camelcase-to-snake-case-in-javascript](url)

**Comment by petergeorgas** [comment]
```ts

const transformToSnakeCase = (obj: any): Object => {
  var snakeCaseObj: any = {};

  for (const key of Object.keys(obj)) {
    var snakeCaseKey = key.replace(
      /[A-Z]/g,
      (char) => `_${char.toLowerCase()}`
    );
    snakeCaseObj[snakeCaseKey] = obj[key];
  }
  return snakeCaseObj;
};


``` 
This is what I've got. should camelCase. It's the RegEx @nwf03 posted above. 

How's this?

**Comment by rajatsharma** [comment]
This is perfect! Just add this code to `post` method and we should be fine.

**Comment by petergeorgas** [comment]
> This is perfect! Just add this code to `post` method and we should be fine.

PR Is now up!

**Comment by petergeorgas** [comment]
@rajatsharma Now that this has been merged in, this issue can be closed.

**Comment by rajatsharma** [comment]
Thanks @petergeorgas!
