### ISSUE TITLE
[refactor]: remove query parameters from request url

### ISSUE THREAD

**Issue by rajatsharma** [keploy/typescript-sdk#7]
At several places we are creating Request url with query parameters using template literals, eg.

https://github.com/keploy/typescript-sdk/blob/5bff7ebfc67c14e9e850de6faa8ed9f2862e3cb4/src/keploy.ts#L71
and
https://github.com/keploy/typescript-sdk/blob/5bff7ebfc67c14e9e850de6faa8ed9f2862e3cb4/src/keploy.ts#L85
and few other places.

Instead we should use `searchParams` option from [got](https://github.com/sindresorhus/got/blob/f582a091500702c88f80526a8d1fd6e040b1eee3/documentation/2-options.md#searchparams)

In order to do so, we have to modify `get` method in `client.ts` to accept `searchParams` too and pass them on to Http options.

**Comment by nwf03** [comment]
fixed this issue and created a pull request

**Comment by rajatsharma** [comment]
Thanks! @nwf03 for the Pull request #10. Closing this.
