### ISSUE TITLE
[refactor]: add get and post methods to Client class instead of Request class

### ISSUE THREAD

**Issue by rajatsharma** [keploy/typescript-sdk#8]
As per [Request](https://github.com/keploy/typescript-sdk/blob/5bff7ebfc67c14e9e850de6faa8ed9f2862e3cb4/src/client.ts#L3) class, you can do this

```ts
const request = new Request().get().post()
```

This is wrong as Request cannot be get and post at the same time. We can fix this like so:

- Throw error when we try to do like above
- Move `get` and `post` method to client and use these methods to make request instead of `makeHttpRequest`

**Comment by re-Tick** [comment]
Merged changes in #4 PR. Closing this issue
