### ISSUE TITLE
[refactor]: Improve typings for TestCase

### ISSUE THREAD

**Issue by rajatsharma** [keploy/typescript-sdk#9]
Currently type of TestCase is `unknown`. We should narrow its type to resemble the test case object.

https://github.com/keploy/typescript-sdk/blob/5bff7ebfc67c14e9e850de6faa8ed9f2862e3cb4/src/keploy.ts#L25

**Comment by re-Tick** [comment]
Added grpc generated files and used them. Made changes in #31. Closing this issue
